### ISSUE TITLE
Two definitions for

### ISSUE THREAD

**Issue by egli** [sbsdev/nordic-accessible-epub-css#1]
The CSS examples have two definitions for `figcaption` (see [CSS Guidelines](https://github.com/sbsdev/nordic-accessible-epub-css/blob/main/CSS_guidelines_draft.org?plain=1#L755). Is this intentional?

``` CSS
  figcaption {
      font-style: italic;
      margin-bottom: 2em;
  }

  figcaption {
      font-size: 0.85rem;
      text-indent: 0;
      margin-top: 0.5em;
      line-height: 1.3;
      font-family: "Source Sans", sans-serif;
  }
```
