### ISSUE TITLE
Two examples for table captions

### ISSUE THREAD

**Issue by egli** [sbsdev/nordic-accessible-epub-css#2]
In the examples section there is an example for table captions and one for captions (see [line 813](https://github.com/sbsdev/nordic-accessible-epub-css/blob/main/CSS_guidelines_draft.org?plain=1#L813) and [line 826](https://github.com/sbsdev/nordic-accessible-epub-css/blob/main/CSS_guidelines_draft.org?plain=1#L826). Is this intentional?

``` CSS
  table caption {
      text-align: left;
      margin-bottom: 0.5em;
      font-weight: bold;
  }
```
and 
``` CSS
  caption {
      font-weight: 700;
      text-align: left;
      background-color: #F5F5F5;
      padding: 0.25em 0.2em 0.25em 0.2em;
      border-top: 1px solid #595959;
      border-bottom: 1px solid #595959;
  }
```
